#ifndef _BUBBLE_TYPE_INCLUDE
#define _BUBBLE_TYPE_INCLUDE

enum BubbleType : unsigned int {
	BUBBLE_BLUE = 0,
	BUBBLE_RED,
	BUBBLE_YELLOW,
	BUBBLE_GREEN,
	BUBBLE_PURPLE,
	BUBBLE_ORANGE,
	BUBBLE_BLACK,
	BUBBLE_GREY,
	BUBBLE_NONE,
	NUM_BUBBLES
};

#endif